import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { fontSans, fontMono } from "@/config/fonts";
import clsx from "clsx";
import MainLayout from "@/components/layout/MainLayout.tsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
      >
        <Providers themeProps={{ attribute: "class", defaultTheme: "light" }}>
          <MainLayout >{children}</MainLayout>
        </Providers>
      </body>
    </html>
  );

}
